apiVersion: v1
kind: Service
metadata:
  name: echo1
  namespace: http-echo
spec:
  ports:
  - port: 80
    targetPort: 5678
  selector:
    app: echo1
---

apiVersion: v1
kind: Service
metadata:
  name: echo2
  namespace: http-echo
spec:
  ports:
  - port: 80
    targetPort: 5678
  selector:
    app: echo2
