
# ============================================================================ #
#               C e r t   M a n a g e r   C h a r t   V a l u e s
# ============================================================================ #

# helm repo add jetstack https://charts.jetstack.io
#
# helm show values jetstack/cert-manager >> cert-manager-values.yaml

---
global:
  priorityClassName: ""

  # Set the verbosity of cert-manager. Range of 0 - 6 with 6 being the most verbose.
  logLevel: 2

installCRDs: true

replicaCount: 1

resources:
  requests:
    cpu: 10m
    memory: 32Mi

prometheus:
  enabled: true
  servicemonitor:
    enabled: false
    prometheusInstance: default
    targetPort: 9402
    path: /metrics
    interval: 60s
    scrapeTimeout: 30s

webhook:
  replicaCount: 1
  resources:
    requests:
      cpu: 10m
      memory: 32Mi

  # Specifies how the service should be handled. Useful if you want to expose the
  # webhook to outside of the cluster. In some cases, the control plane cannot
  # reach internal services.
  serviceType: ClusterIP
  # loadBalancerIP:

  # Overrides the mutating webhook and validating webhook so they reach the webhook
  # service using the `url` field instead of a service.
  url: {}
    # host:

cainjector:
  enabled: true
  replicaCount: 1

  resources:
    requests:
      cpu: 10m
      memory: 32Mi